### ISSUE TITLE
gwtop KeyError: 'overall_status'

### ISSUE THREAD

**Issue by hydro-b** [ceph/ceph-iscsi-tools#5]
On CentOS 7.5 with ceph-iscsi-tools (master) a gwtop --debug results in:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gwtop-2.1-py2.7.egg/EGG-INFO/scripts/gwtop", line 48, in run_with_except_hook
    
  File "build/bdist.linux-x86_64/egg/gwtop/UI/textmode.py", line 170, in run
  File "build/bdist.linux-x86_64/egg/gwtop/UI/textmode.py", line 148, in update_ceph
  File "build/bdist.linux-x86_64/egg/gwtop/config/ceph.py", line 30, in _get_health
KeyError: 'overall_status'

Note: one of the gateways is a Ubuntu 18.04 LTS

**Comment by hydro-b** [comment]
gwtop --debug on the Ubuntu 18.04 LTS host results in:

gwtop --debug
Traceback (most recent call last):
  File "/usr/local/bin/gwtop", line 4, in <module>
    __import__('pkg_resources').run_script('gwtop==2.1', 'gwtop')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/gwtop-2.1-py2.7.egg/EGG-INFO/scripts/gwtop", line 282, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/gwtop-2.1-py2.7.egg/EGG-INFO/scripts/gwtop", line 162, in get_options
    
KeyError: 'lun_type'

(the shebang for gwtop has been changed to #!/usr/bin/python2)

**Comment by pcuzner** [comment]
_get_health just issues a status command to ceph and parses the output. What version of ceph is installed?

**Comment by pcuzner** [comment]
for the lun_type error, can you tell me whether you have configured any luns yet?

Do you have entries under /sys/kernel/config/target/core/iblock* or /sys/kernel/config/target/core/user*

**Comment by hydro-b** [comment]
On Tue, May 22, 2018 at 07:48:38PM -0700, pcuzner wrote:
> for the lun_type error, can you tell me whether you have configured any luns yet?
> 
> Do you have entries under /sys/kernel/config/target/core/iblock* or /sys/kernel/config/target/core/user*

Yes:

ls /sys/kernel/config/target/core/user*
/sys/kernel/config/target/core/user_0:
hba_info  hba_mode  rbd.disk_1

/sys/kernel/config/target/core/user_1:
hba_info  hba_mode  rbd.disk_2

/sys/kernel/config/target/core/user_2:
hba_info  hba_mode  rbd.disk_3

/sys/kernel/config/target/core/user_3:
hba_info  hba_mode  rbd.disk_4

/sys/kernel/config/target/core/user_4:
hba_info  hba_mode  rbd.disk_5

**Comment by hydro-b** [comment]
On Tue, May 22, 2018 at 07:46:18PM -0700, pcuzner wrote:
> _get_health just issues a status command to ceph and parses the output. What version of ceph is installed?

12.2.5-0.el7 (CentOS gateways) based on Ceph repo packages from a mirror based on
download.ceph.com`
